### ISSUE TITLE
B2D signup

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#137]
### Description

For the upcoming ETH Denver event, the RPCh founders would like to offer people at the event poaps which will link them to a website. Through that website, people will be able to register (give contact details) and gain a `secret key` which will give them access to `RPCh` for limited free time. Afterwards, once freemium runs out, they receive a notification via the contact details given.

With this `secret key`, users can enter it in RPCh's entry node docker image (`apps/rpc-node`) and then they can use the created RPC server URL in their wallet of choice.

Flow:

1. Person receives `poap`
2. Person claims `poap` & sees link to `rpch.net/access`
3. Website asks to register by adding your (join TG channel for news)
4. User gets a `secret key`
5. User goes to `apps/rpc-node` and follows the instructions to run the `rpc-node` docker image with the secret key
5. Following the instructions, the user adds RPC server URL into wallet of choice

Affect in STARMAP:

1. Kevlar/Helios kicked out from February and replaced by POAP signup
2. When freemium is switched off, we need to have payment gateway for the user, this can only be available by end of March

### Relevant issues

- [x] #169
- [x] https://github.com/Rpc-h/access-rpch-net/issues/1
- [x] #167

### Definition of DONE

Once the individual components are part of the codebase. The website should be accessible at access.hoprnet.org and point to our alpha discovery platform.

**Comment by SCBuergel** [comment]
> once freemium runs out, they receive a notification via the contact details given

How is that notification shown to the user?

**Comment by SCBuergel** [comment]
> give contact details

Why is that needed? IMO we should be as anon friendly as possible for this product

**Comment by SCBuergel** [comment]
> When freemium is switched off, we need to have payment gateway for the user, this can only be available by end of March

Potential solution: we keep using POAPs but users have to purchase these POAPs after the free period / quota got used up.

**Comment by SCBuergel** [comment]
How do we link POAP id to secret? I.e., how do we prevent double spends or free riders?

Option 1: transfer POAP somewhere, similar to redeeming HOPR boost NFTs. Practically that's hard because the POAP app doesn't allow for transfers.

Option 2: all users to sign a message from the address at which they're holding their POAP (make sure to follow relevant EIPs with domain separation etc). The signature is submitted to a webservice which validates the signature and checks if the POAP id is listed in a DB as an available id and issues a valid secret for that user. Probably the better option. TODO: find out if we need to enter the POAP id into db ourselves or if there's a way to treat metadata of the POAP (we need to make sure it's actually a valid RPCh POAP and not some random other one) from the webservice and write it to the db.

**Comment by nionis** [comment]
@SCBuergel replying to the comments:

1 & 2. once we agree on what contact details to share, we use those to notify them
3. its important to note that B2D is purely a marketing campaign and not actually of value to the long term vision for RPCh, with the suggested solution, this will require additional development, would rather not do that and instead wait to introduce the payment gateway
4. it really depends how secure we want this whole process to be, this is a marketing campaign, I would rather keep it simple:
 1. they go to a website
 2. sign up
 3. discovery platform gives them a secret
