### ISSUE TITLE
[DRAFT] Expand E2E test suite

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#206]
### Description

TBD

### Relevant issues
TBD

### Definition of DONE
TBD

**Comment by ItsLuized** [comment]
Some research notes:

## Tools for E2E tests:

1. Jest: Jest is a popular JavaScript testing framework that can be used to test your SDK code. It supports TypeScript out of the box and includes features such as mocking and snapshot testing that can be useful for testing SDK functionality.
2. Mocha: Mocha is another popular JavaScript testing framework that can be used to test your SDK code. It supports TypeScript with the help of plugins, and it has a wide range of integrations and extensions that can be used to extend its functionality.
3. Sinon: Sinon is a JavaScript library that provides standalone test spies, stubs, and mocks. It can be used to simulate different scenarios and test different parts of your SDK code.
4. Supertest: Supertest is a lightweight library for testing HTTP servers in Node.js. It can be used to test your SDK's API calls and simulate responses from the server.

We are using jest to make the petitions to the SDK.

## Types of tests (suggested ones and to consider using)
### Snapshot testing
Snapshot tests are a very useful tool whenever you want to make sure your UI does not change unexpectedly.
A typical snapshot test case renders a UI component, takes a snapshot, then compares it to a reference snapshot file stored alongside the test. The test will fail if the two snapshots do not match: either the change is unexpected, or the reference snapshot needs to be updated to the new version of the UI component.
_Source: https://jestjs.io/docs/snapshot-testing#best-practices_

Since Snapshot testing focuses on UI changes, it is not an option. Additionally, this tests are not meant to be run on CI.

### Performance testing
Performance tests evaluate how a system performs under a particular workload. These tests help to measure the reliability, speed, scalability, and responsiveness of an application. For instance, a performance test can observe response times when executing a high number of requests, or determine how a system behaves with a significant amount of data. It can determine if an application meets performance requirements, locate bottlenecks, measure stability during peak traffic, and more. 

### Smoke testing
Smoke tests are basic tests that check the basic functionality of an application. They are meant to be quick to execute, and their goal is to give you the assurance that the major features of your system are working as expected.
Smoke tests can be useful right after a new build is made to decide whether or not you can run more expensive tests, or right after a deployment to make sure that they application is running properly in the newly deployed environment.

_Source: https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing_

I think performance testing can be a good addition. 

Ideas:  
- Send 20+ transactions and in the last one, measure the response time… If it’s under 10s it’s good.
- Send a huge transaction (COW swap equivalent)
