### ISSUE TITLE
visualise requests sent vs failed

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#213]
### Is your feature related to a problem?

No

### Describe the feature you'd like

Build a re-usable tool which can generate a visualization for the requests sent, failed, their size, entry node score, etc

**Comment by diegoalzate** [comment]
# Metrics

software: prometheus

## Discovery platform

Pull model, open a port that will receive metrics

### what will we track?

- registered nodes registration counter
- quota counter (added/subtracted)
- failed requests in general any http request that is failing
- clients counter
- amount we told funding service to fund

## Funding service

### what will we track?

Pull model, open a port that will receive metrics

- number of nodes we have funded
- counter of failed funds
- avg how much we fund in a day

## SDK

### what will we track?

- Requests sent
- avg request size
- failed requests
- request time

### Possible solution for sdk

Since SDK does not run in a centralized way and in general can be used by any wallet. A possible solution is to accept a flag so users can contribute to these metrics. For this to follow hopr policy all metrics that are being sent need to be anon and server has to be public and open source.

steps required to complete possible solution:

- sdk metrics server
- add metrics to sdk
- add sdk flag so anyone running anything using the sdk can choose to contribute to metrics
