### ISSUE TITLE
Issues identified in hoprd-riga 1.92.12

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#285]
### Description

The goal of this task is to provide a global overview of all the issues that have been found while the rpch team uses the release riga 1.92.12

### Procedure
- Creating a comment on the issue providing all kind of information from the point of view of rpch team:
   - Starting time
   - Response time
   - Nodes affected
   - Operations performing bad in rpch features 
   - How to reproduce the issue by the core-team
   - Information about how to access to the node logs
- Mentioning in the testing channel that you have found a new instability problem
- If the issue is identified in core-team working hours, then someone from the core-team will look into it before restarting the nodes. That is an important step, as it's easier to identify the problem when the node is behaving bad than from looking just at the logs. After gathering all the required information, it will instruct someone from the rpch teams to restart the nodes.
- If it is identified out of core-team working hours, then there are several options.
   - Follow the steps before, but waiting until one of the core-team members can look into it.
   - Follow the steps before but collecting the logs and restart the nodes.
   - Skip this instability issue and just restart the nodes.

**Comment by nionis** [comment]
Adding big logs files in [here](https://drive.google.com/drive/u/2/folders/1UOCDTduLSLaJkiUT5HSV9DbjKhomqFuu)

**Comment by Jaguaras** [comment]
### Expected behaviour:

Response latency time should be < 5 sec

### Current status:

From 2023-03-22 9AM CET response latency has increased up to 20 sec.

Tool for monitoring:  https://monitor.rpch.tech

What I did:
1. I tried to start RPCh server with a docker command and tried a simple swap on sushi.swap, currently you have to wait >1 min until it will be able to collect gas fees for a successful swap. 

### Possible Solution

Restarting RPCh nodes, everything works as expected and latency is < 5 sec.

### Detailed Description

Version of the nodes: **1.92.12**

**Comment by diegoalzate** [comment]
Expected behaviour:
Response latency time should be < 5 sec

Current status:
From 23 March 2023, 4:48 AM

Tool for monitoring: https://monitor.rpch.tech/

Discovery platform returns nodes so the only thing that can be making latencies increase in hoprd nodes

restarted nodes and added logs to drive

Detailed Description
Version of the nodes: 1.92.12

**Comment by ItsLuized** [comment]
### Expected behaviour:
Response latency time should be < 5 sec

### Current status:
From 2023-03-23 2:30PM CET response latency has increased up to 20 sec.

Tool for monitoring: https://monitor.rpch.tech/

Restarting RPCh nodes at 4:00PM CET, everything works as expected and latency is < 5 sec.
Logs added to Drive

Detailed Description
Version of the nodes: 1.92.12

**Comment by diegoalzate** [comment]
Expected behaviour:
Response latency time should be < 5 sec

Current status:
From 31 March 2023, 10:15pm GMT

Tool for monitoring: https://grafana.rpch.tech/ and element alert

Discovery platform returns nodes so the only thing that can be making latencies increase in hoprd nodes

restarted nodes and added logs to drive

Detailed Description
Version of the nodes: 1.92.12

**Comment by nionis** [comment]
Obsolete as new HOPRd version do not crash frequently.
